### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by JaxkDev** [Adam-Seddon/CMP1903M-A01-2223#1]
In terms of documentation there is a fair amount correctly describing the function of each section.
eg 
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L34
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Program.cs#L13
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/testing.cs#L13

For error handling, have you considered this comment and thought about having some setter validation ?
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Card.cs#L14-L16

Also on this dealCard method have you considered checking the input amount as to avoid an index out of range error.
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L68-L78

A little bit of code improvement, have you thought about reducing this to a single `return true;` 
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L54-L58

But otherwise a really nice implementation and runs locally :)

Jack Honour 27203747

**Comment by Adam-Seddon** [comment]
Added some validation and reduced the section at the end of the shuffle method to a single return true.
Thanks
