### ISSUE TITLE
Code Review 2

### ISSUE THREAD

**Issue by Carter-Stone** [Adam-Seddon/CMP1903M-A01-2223#2]
In general, the commenting serves its purpose and gives a brief and accurate summary of the intention for the following code. 
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L28-L31
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L15
There is enough to assist the average reader however if I had to improve the commenting, I would comment within some of the classes and methods alongside complex phrases and give a short explanation of what is going on in a specific line. This could also just cause a slew of too many unnecessary comments.

The Pack is created in the constructor.

https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L9-L24

All of the following have the required signatures
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L26 
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L68
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L60

Both Fisher-Yates and Riffle are available shuffle options as well as No shuffle. However, one change I would make would be to add some Error handling encase shuffle type is not a valid type. Also in the dealCard method
https://github.com/Adam-Seddon/CMP1903M-A01-2223/blob/9763f12029896e1cdb3ea248f5d8dbb4bc7c2105/CMP1903M%20A01%202223/Pack.cs#L68-L77
you could check the "amount" input argument to see if it is in the range of the pack.

There is a testing class where all three shuffle types are performed, one card is dealt and then the rest of the pack. 

This is the terminal when running the test class.
![image](https://user-images.githubusercontent.com/122040857/223743508-4ba0fa1e-f3a3-46fe-91a9-9f110e5447bf.png)
To improve the user experience I would create a list of enumerators for the suits and value so that it would print as "Jack of Spades" rather than "11 of  2"

Good Work 👍
Carter Stone #26511753

**Comment by Adam-Seddon** [comment]
I have added error handling as suggested as well as changing the display to show e.g. 'Ace of CLubs' instead of '1 of 1'.
Thank You
